# Generated by Django 2.2.24 on 2021-07-18 03:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('contruccion_anio', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2021)], verbose_name='Año del construcción')),
                ('estado', models.PositiveIntegerField(blank=True, choices=[(0, 'pre_venta'), (1, 'en_venta'), (2, 'vendido')], null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estado de la propiedad')),
                ('precio', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio')),
                ('direccion', models.CharField(max_length=80)),
                ('entidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casas.Estado', verbose_name='Entidad federativa')),
            ],
        ),
    ]
