# Generated by Django 2.2.24 on 2021-07-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casas', '0003_auto_20210718_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='cuidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='casas.Ciudad', verbose_name='Cuidad'),
        ),
    ]
